name: Greetings

on:
  pull_request:
    branches: 
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
     - uses: lob/action_sam_jackson@0.0.2
       with:
          message: 'Bravo mashine!'
          token: ${{secrets.GITHUB_TOKEN}}
